server:
  port: 8426

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://47.104.205.27:3306/chilx-jw?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: Root123456!
    hikari:
      connection-timeout: 60000
    show-sql: true



#==============================mybatis驼峰式类名自动映射数据库字段=============================
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 新增返回主键
    use-generated-keys: true
  type-aliases-package: com.gpos.entity.pg
  mapper-locations: classpath*:com/gpos/dao/**/*.xml


mapper:
  mappers:
    - com.chilx.jw.common.base.mybatis.BaseInfoMapper
  not-empty: false

pagehelper:
  helperDialect: mysql
  # 分页合理化参数，默认值为false。
  # 当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。
  # 默认false 时，直接根据参数进行查询
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#==============Mybatis 配置结束==========================================

